@users = http://localhost:8000/users
@token = {{login.response.body.$.token}}

GET {{users}}/abc.json
Authorization: Bearer {{token}}

###
# @name login
GET https://taz.harding.edu/tas/login?username=jdees&admin=true&expiresIn=1hr